### ISSUE TITLE
Support Workspace Commands

### ISSUE THREAD

**Issue by charleszipp** [jason-johnson/azure-pipelines-tasks-terraform#12]
As a release engineer, I would like to be able to create and select a terraform workspace, so that I can test features in isolated infrastructure.

## Supported Sub-Commands
Workspace commands will be added in the following order
- [x] select
- [x] new
- [ ] new succeeds when workspace exists with toggle to fail if exists (backwards compatibility)
- [ ] show
- [ ] delete
- [ ] list

Select is being used first so those with existing workspaces can use this immediately after that work is completed.

## Expected YAML Syntax

The following is the yaml expected to use workspaces. Final syntax will be added to the Overview doc paired with examples in pipelines/test directory.

### Workspace Select
```yaml
- task: TerraformCLI@0
  displayName: 'terraform workspace select'
  inputs:
    command: workspace
    workspaceName: foo
    workspaceSubCommand: select
    workingDirectory: $(terraform_templates_dir)
```
