### ISSUE TITLE
Warning issued on 'TerraformCLI@0' task running 'plan' that has no changes

### ISSUE THREAD

**Issue by rafabu** [jason-johnson/azure-pipelines-tasks-terraform#43]
**Describe the bug**
Since updating to extension version 0.6.24, I am seeing a warning issued after an otherwise successful ```terraform plan``` task that does not have any changes. This leads to following tasks failing (picking up the warning).

**To Reproduce**
When on extension version 0.6.24:
* run a TerraformCLI@0 task to plan that does not produce any changes (infrastructure is up-to-date)
* Example task (using detailed-exitcode):
```YAML
- task: TerraformCLI@0
  continueOnError: true
  inputs:
    command: 'plan'
    commandOptions: '-out=tfplan.bin -input=false -detailed-exitcode'
    workingDirectory: '$(tfModulePath)'
    environmentServiceName: '${{ parameters.devopsServiceConnection }}'
    publishPlanResults: '${{ parameters.devopsArtifact }}'
  env:
    TF_IN_AUTOMATION: 'True'
    TF_CLI_ARGS_plan: '$(TF_CLI_ARGS_plan)'
    tenant_id: '$(tenant_id)'
    subscription_id: '$(subscription_id)'
    client_id: '$(client_id)'
    client_secret: '$(client_secret)'
  name: 'tfPlanTargeted'
  displayName: 'tf - plan'
```

**Expected behavior**
Task should not return with a warning if _infrastructure is up-to-date_

**Screenshots**
![image](https://user-images.githubusercontent.com/43059250/119544406-f435b480-bd91-11eb-995f-1864b7e1cc79.png)

**Agent Configuration**
 - ubuntu-latest
 - hosted
 - 0.14.11 (we are not currently able to use 0.15,x for reasons not related this extension)
 - default
