### ISSUE TITLE
Terraform environment variable TERRAFORM_PLAN_HAS_CHANGES is not created when terraform plan is executed

### ISSUE THREAD

**Issue by kovaliovsg** [jason-johnson/azure-pipelines-tasks-terraform#45]
**Describe the bug**
Starting with version 0.6.23 environment variable TERRAFORM_PLAN_HAS_CHANGES is not created and populated with false or true.

This block will succeed:
```
    - task: TerraformCLI@0.6.23
      displayName: "Terraform Plan"
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/${{parameters.configuration_folder}}'
        environmentServiceName: '${{variables.subscription_name}}'
        commandOptions: '--var-file=vars_env_${{parameters.subscription_code}}.tfvars -out=$(System.DefaultWorkingDirectory)/${{parameters.configuration_folder}}/terraform.tfplan'
        publishPlanResults: 'terraform_plan'
    - task: PowerShell@2
      displayName: 'Set variable output_terraform_plan_has_changes'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Terraform changes detected: $(TERRAFORM_PLAN_HAS_CHANGES)"
```

This block will fail:

```
    - task: TerraformCLI@0.6.24
      displayName: "Terraform Plan"
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/${{parameters.configuration_folder}}'
        environmentServiceName: '${{variables.subscription_name}}'
        commandOptions: '--var-file=vars_env_${{parameters.subscription_code}}.tfvars -out=$(System.DefaultWorkingDirectory)/${{parameters.configuration_folder}}/terraform.tfplan'
        publishPlanResults: 'terraform_plan'
    - task: PowerShell@2
      displayName: 'Set variable output_terraform_plan_has_changes'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Terraform changes detected: $(TERRAFORM_PLAN_HAS_CHANGES)"
```

Exception message:
```
TERRAFORM_PLAN_HAS_CHANGES : The term 'TERRAFORM_PLAN_HAS_CHANGES' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At D:\a\_temp\cf205a36-eb72-43a3-99bd-1e47c15f25f7.ps1:3 char:43
+ ... rite-Host "Terraform changes detected: $(TERRAFORM_PLAN_HAS_CHANGES)"
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TERRAFORM_PLAN_HAS_CHANGES:String) [], ParentContainsErrorRecordExcepti 
   on
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by rafabu** [comment]
On top of failing to make ```TERRAFORM_PLAN_HAS_CHANGES``` available, the version 0.6.23 also seems to no longer expose ```TERRAFORM_LAST_EXITCODE``` (when used with '-detailed-exitcode').

**Comment by kovaliovsg** [comment]
Yes, I mentioned that as well, however I don't rely on that variable TERRAFORM_LAST_EXITCODE, I need this variable to work in the new version: TERRAFORM_PLAN_HAS_CHANGES

**Comment by charleszipp** [comment]
Will be working on this today. Similar to #46, my plan is to support both emit as both variable and output for backwards compatibility if this is supported.

**Comment by Daniel157** [comment]
@kovaliovsg How did you specify the version of the TerraformCLI task to use? When I try to specify `TerraformCLI@0.6.23` (with version number) as task, it will always tell me that my pipeline is invalid (`String does not match the pattern of "^PowerShell@2$".`).
When I save the pipeline YML anyway and try to run it, it will say:

```
Invalid step task reference TerraformCLI@0.6.23
```

It only accepts it when I specify it like this: `TerraformCLI@0` (which will use the latest, currently broken version)
Is there something additional I have to do to be able to specify an older version of the TerraformCLI task?

**Comment by kovaliovsg** [comment]
Unfortunately specifying a version is possible in the standard job only. It doesn't work in the deployment job. I have opened a ticket to Microsoft to figure it out why it works in a standard job but not in the deployment job.

**Comment by charleszipp** [comment]
Unfortunately, it appears azure pipelines does not allow you to set a variable and output with the same name. If I set `TERRAFORM_PLAN_HAS_CHANGES` twice, once with `isOutput=false` and once with `isOutput=true`, the same issue still occurs. So likely last one wins. 
**Will be reverting the changes the output changes so everyone is unblocked while I figure out a different strategy.**

**Comment by OmnipotentOwl** [comment]
Would it be possible to just add a new input parameter to the task to support user control over whether to use output variables or not?

**Comment by OmnipotentOwl** [comment]
@kovaliovsg  to fix your pipeline to be compatible with 0.6.24 you would make the following changes.
Note the "name" parameter which is the reference name in devops and the change to the variable to mark the reference to it.
```
- task: TerraformCLI@0.6.24
  displayName: "Terraform Plan"
  name: tfplan
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/${{parameters.configuration_folder}}'
    environmentServiceName: '${{variables.subscription_name}}'
    commandOptions: '--var-file=vars_env_${{parameters.subscription_code}}.tfvars -out=$(System.DefaultWorkingDirectory)/${{parameters.configuration_folder}}/terraform.tfplan'
    publishPlanResults: 'terraform_plan'
- task: PowerShell@2
  displayName: 'Set variable output_terraform_plan_has_changes'
  inputs:
    targetType: 'inline'
    script: |
       Write-Host "Terraform changes detected: $(tfplan.TERRAFORM_PLAN_HAS_CHANGES)"
```
