### ISSUE TITLE
`terraform import` doesn't support `runAzLogin: true`

### ISSUE THREAD

**Issue by dvasdekis** [jason-johnson/azure-pipelines-tasks-terraform#54]
**Describe the bug**
Running import *without* `runAzLogin: true` I get:
```
 Error: Error building AzureRM Client: obtain subscription(*azure sub id*) from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
``` 
But running import *with*  `runAzLogin: true` I get the same error.

**To Reproduce**
Try the below pipeline:
```
trigger:
- master
pool:
  vmImage: windows-latest
parameters:
- name: 'environments'
  type: object
  default: 
  - dev
  - tst
  - prd

steps:
- ${{ each env in parameters.environments }}:
  - task: TerraformInstaller@0
    displayName: install terraform
  - task: TerraformCLI@0
    displayName: 'Terraform set workspace to ${{ env }}'
    inputs:
      workingDirectory: $(Build.SourcesDirectory)/infra
      command: workspace
      workspaceSubCommand: new
      workspaceName: ${{ env }}
  - task: TerraformCLI@0
    displayName: 'terraform init ${{ env }}'
    inputs:
      workingDirectory: $(Build.SourcesDirectory)/infra
      command: init
      backendType: local
  - task: TerraformCLI@0
    displayName: 'terraform import ${{ env }}'
    inputs:
      command: import
      workingDirectory: $(Build.SourcesDirectory)/infra
      resourceAddress: azurerm_resource_group.myrg
      resourceId: "/subscriptions/*redacted*/resourceGroups/myrg"
      runAzLogin: true
```
**Expected behavior**
I want to be able to import my resource groups, like I can on desktop.

**Pipeline Logs**
```
C:\hostedtoolcache\windows\terraform\0.15.5\x64\terraform.exe version
Terraform v0.15.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
C:\hostedtoolcache\windows\terraform\0.15.5\x64\terraform.exe import azurerm_resource_group.myrg /subscriptions/*redacted*/resourceGroups/myrg

│ Error: Error building AzureRM Client: obtain subscription(*redacted*) from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on D:\a\1\s\infra\main.tf line 67, in provider "azurerm":
│   67: provider "azurerm" {

Finishing: terraform import dev
```

**Agent Configuration**
All default versions, Azure hosted
