### ISSUE TITLE
Failure in 'terraform plan' stage when azure storage backend is chosen

### ISSUE THREAD

**Issue by Arash-Sabet** [jason-johnson/azure-pipelines-tasks-terraform#57]
**Describe the bug**
When initializing 'terraform init' step with azure storage account info as the backend, 'terraform plan' stage fails.

**To Reproduce**
Run the following script:

```
task: TerraformInstaller@0
  displayName: Download terraform
  inputs:
    terraformVersion: '0.15.5'
    downloadUrl: 'https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip'
- task: TerraformCLI@0
  displayName: 'Terraform init'
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Development and test (MASKED)'
    backendAzureRmResourceGroupName: 'myresourcegroup'
    backendAzureRmStorageAccountName: 'myaccountname'
    backendAzureRmContainerName: 'multitstate'
    backendAzureRmKey: 'terraform.state'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  displayName: 'Terraform plan'
  inputs:
    command: 'plan'
    environmentServiceName: 'Development and test (MASKED)'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  displayName: 'Terraform apply'
  name: terraformApply
  inputs:
    command: 'apply'
    environmentServiceName: 'Development and test (MASKED)'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  displayName: 'Terraform output'
  inputs:
    command: 'output'
    allowTelemetryCollection: false
```

**Expected behavior**
The pipeline should not fail.

**Screenshots**
n/a

**Pipeline Logs**

> Starting: Terraform plan
> ==============================================================================
> Task         : Terraform CLI
> Description  : Execute terraform cli commands
> Version      : 0.6.25
> Author       : Charles Zipp
> Help         : 
> ==============================================================================
> /opt/hostedtoolcache/terraform/0.15.5/x64/terraform version
> Terraform v0.15.5
> on linux_amd64
> 
> Your version of Terraform is out of date! The latest version
> is 1.0.0. You can update by downloading from https://www.terraform.io/downloads.html
> 
> /opt/hostedtoolcache/terraform/0.15.5/x64/terraform plan
> ╷
> │ Error: No configuration files
> │ 
> │ Plan requires configuration to be present. Planning without a configuration
> │ would mark everything for destruction, which is normally not what is
> │ desired. If you would like to destroy everything, run plan with the
> │ -destroy option. Otherwise, create a Terraform configuration file (.tf
> │ file) and try again.
> ╵
> 
> ##[error]Terraform command 'plan' failed with exit code '1'.
> ##[error]╷
> │ Error: No configuration files
> │ 
> │ Plan requires configuration to be present. Planning without a configuration
> │ would mark everything for destruction, which is normally not what is
> │ desired. If you would like to destroy everything, run plan with the
> │ -destroy option. Otherwise, create a Terraform configuration file (.tf
> │ file) and try again.
> ╵
> 
> Finishing: Terraform plan
> 
> **Agent Configuration**
>  - OS: [e.g. ubuntu debian]
>  - Hosted/Self Hosted
>  - Terraform version used (Default for hosted agent is acceptable)
>  - AzureCLI version used (Default for hosted agent is acceptable or N/A)

**Additional context**
n/a
