### ISSUE TITLE
`SyntaxError: Unexpected token M in JSON at position 82780` when doing a `terraform show ./tfplan`

### ISSUE THREAD

**Issue by ausfestivus** [jason-johnson/azure-pipelines-tasks-terraform#61]
**Describe the bug**

Azure DevOps is reporting an error when the pipeline runs a `terraform show -json ./tfplan` task. The error says:

```
2021-07-01T06:22:45.4636143Z ##[error]SyntaxError: Unexpected token M in JSON at position 82780
```

Full debug output from the task is available at https://gist.github.com/ausfestivus/9eca2d6d03aa81ff7a2c3251335b5eb9

**To Reproduce**

The error occurs with this terraform code. When I run the same pipeline YAML with a different set of terraform files the problem does not occur.

**Expected behavior**

The error should not occur and the terraform command should succeed.

**Screenshots**

n/a

**Pipeline Logs**

See gist https://gist.github.com/ausfestivus/9eca2d6d03aa81ff7a2c3251335b5eb9

**Agent Configuration**

 - OS: ubuntu 20 LTS
 - Self hosted
 - 0.13.7
 - AzureCLI version used (Default for hosted agent is acceptable or N/A)

**Additional context**

I suspect this is an AzDO problem but I am stuck on how to troubleshoot further. A google search turned up a link to this repo at https://github.com/charleszipp/azure-pipelines-tasks-terraform/issues/171 but that URL 404s. Its probably an issue in the old repo.

**EDIT**

* corrected the command that is being run that produces the error

**Comment by ausfestivus** [comment]
Ive been trying to get some more information about whats happening here.

* the problem does not occur when I run the same command on my local CLI
* There appears to be a difference between the documented command and what is actually getting run by the agent.
** The task in the pipeline YAML says:
```
          # Run show to detect destroy operations
          - task: TerraformCLI@0
            name: tfShowPlan
            displayName: terraform show plan
            inputs:
              command: show
              inputTargetPlanOrStateFilePath: ./tfplan
```
  when running the pipeline with `debug=true` we see
```
##[debug]exec tool: /opt/agent/_work/_tool/terraform/0.13.7/x64/terraform
##[debug]arguments:
##[debug]   show
##[debug]   -json
##[debug]   ./tfplan
```
* where is that `-json` switch coming from? Am I missing something about AzDO pipeline behaviour?

**Comment by StephanZaat** [comment]
I have a very similar issue, but I am also unsure where to fix this:

```
      - task: TerraformCLI@0
        displayName: 'Terraform Pre-Apply - Plan'
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: 'tf-infra/tfblocks/${{ resource }}'
          environmentServiceName: '$(azureSub)'
          commandOptions: '-out=$(System.DefaultWorkingDirectory)/terraform.tfplan'
          publishPlanResults: 'Terraform_Plan'
```
```
      - task: TerraformCLI@0
        displayName: 'Terraform Pre-Apply - Detect Destroy'
        inputs:
          command: 'show'
          inputTargetPlanOrStateFilePath: '$(System.DefaultWorkingDirectory)/terraform.tfplan'
```
          
Debug output: 
```
##[debug]arguments:
##[debug]   show
##[debug]   -json
##[debug]   /home/vsts/work/1/s/terraform.tfplan

##[error]SyntaxError: Unexpected end of JSON input
```
